import type { IQuest } from '@/types/quest';

export const QUESTS: IQuest[] = [
	{
		range: 'day',
		metric: 'volume',
		metrics: ['volume'],
		name: 'Daily',
		reward: 10000,
	},
	{
		range: 'week',
		metric: 'volume',
		metrics: ['volume'],
		name: 'Weekly',
		reward: 10000,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyThree',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 22',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyThree',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 22',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFour',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 23',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFour',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 23',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFive',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 24',
		reward: 25000 * 0.6,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFive',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 24',
		reward: 25000 * 0.4,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySix',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 25',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySix',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 25',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySeven',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 26',
		reward: 25000 * 0.6,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySeven',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 26',
		reward: 25000 * 0.4,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyEight',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 27',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyEight',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 27',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyNine',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 28',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyNine',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 28',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirty',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 29',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirty',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 29',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyOne',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 30',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyOne',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 30',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyTwo',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 31',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyTwo',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 31',
		reward: 25000 * 0.5,
	},
];
