import { subDays } from 'date-fns';

import type { IQuest } from '@/types/quest';

export const QUESTS: IQuest[] = [
	{
		range: 'day',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		name: 'Daily',
		reward: 10000,
		startDate: subDays(new Date(), 1),
		endDate: new Date(),
	},
	{
		range: 'day',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		name: 'Daily',
		reward: 10000,
		startDate: subDays(new Date(), 1),
		endDate: new Date(),
	},
	{
		range: 'week',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		name: 'Weekly',
		reward: 10000,
		startDate: subDays(new Date(), 7),
		endDate: new Date(),
	},
	{
		range: 'week',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		name: 'Weekly',
		reward: 10000,
		startDate: subDays(new Date(), 7),
		endDate: new Date(),
	},
	{
		range: 'month',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		name: 'Monthly',
		reward: 10000,
		startDate: subDays(new Date(), 30),
		endDate: new Date(),
	},
	{
		range: 'month',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		name: 'Monthly',
		reward: 10000,
		startDate: subDays(new Date(), 30),
		endDate: new Date(),
	},
	{
		name: 'Bonus Round',
		range: 'limboDayTwo',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		winners: 1000,
		subname: 'Day 1',
		reward: 25000,
		startDate: new Date(1748476800000),
		endDate: new Date(1748563200000),
	},
	{
		name: 'Bonus Round',
		range: 'limboDayTwo',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		winners: 500,
		subname: 'Day 1',
		reward: 25000,
		startDate: new Date(1748476800000),
		endDate: new Date(1748563200000),
	},
	{
		name: 'Bonus Round',
		range: 'limboDayTwo',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		winners: 1000,
		subname: 'Day 2',
		reward: 33000,
		startDate: new Date(1748563200000),
		endDate: new Date(1748649600000),
	},
	{
		name: 'Bonus Round',
		range: 'limboDayTwo',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		winners: 500,
		subname: 'Day 2',
		reward: 33000,
		startDate: new Date(1748563200000),
		endDate: new Date(1748649600000),
	},
	{
		name: 'Bonus Round',
		range: 'limboDayThree',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		winners: 1000,
		subname: 'Day 3',
		reward: 33000,
		startDate: new Date(1748649600000),
		endDate: new Date(1748736000000),
	},
	{
		name: 'Bonus Round',
		range: 'limboDayThree',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		winners: 500,
		subname: 'Day 3',
		reward: 33000,
		startDate: new Date(1748649600000),
		endDate: new Date(1748736000000),
	},
];
