import type { IQuest } from '@/types/quest';

export const QUESTS: IQuest[] = [
	{
		range: 'day',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		name: 'Daily',
		reward: 10000,
	},
	{
		range: 'day',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		name: 'Daily',
		reward: 10000,
	},
	{
		range: 'week',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		name: 'Weekly',
		reward: 10000,
	},
	{
		range: 'week',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		name: 'Weekly',
		reward: 10000,
	},
	{
		range: 'month',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		name: 'Monthly',
		reward: 10000,
	},
	{
		range: 'month',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		name: 'Monthly',
		reward: 10000,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyThree',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 22',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyThree',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 22',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFour',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 23',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFour',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 23',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFive',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 24',
		reward: 25000 * 0.6,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyFive',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 24',
		reward: 25000 * 0.4,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySix',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 25',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySix',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 25',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySeven',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 26',
		reward: 25000 * 0.6,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentySeven',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 26',
		reward: 25000 * 0.4,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyEight',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 27',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyEight',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 27',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyNine',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 28',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignTwentyNine',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 28',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirty',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 29',
		reward: 25000 * 0.2,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirty',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 29',
		reward: 25000 * 0.8,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyOne',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 30',
		reward: 25000 * 0.4,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyOne',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 30',
		reward: 25000 * 0.6,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyTwo',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 31',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyTwo',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 31',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyThree',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 32',
		reward: 25000 * 0.2,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyThree',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 32',
		reward: 25000 * 0.8,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyFour',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 33',
		reward: 25000 * 0.2,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyFour',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 33',
		reward: 25000 * 0.8,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyFive',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 34',
		reward: 25000 * 0.2,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyFive',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 34',
		reward: 25000 * 0.8,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtySix',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 35',
		reward: 25000 * 0.8,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtySix',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 35',
		reward: 25000 * 0.2,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtySeven',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 36',
		reward: 25000 * 0.2,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtySeven',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 36',
		reward: 25000 * 0.8,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyEight',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 37',
		reward: 25000 * 0.4,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyEight',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 37',
		reward: 25000 * 0.6,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyNine',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 38',
		reward: 25000 * 0.4,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignThirtyNine',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 38',
		reward: 25000 * 0.6,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignForty',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 39',
		reward: 25000 * 0.8,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignForty',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 39',
		reward: 25000 * 0.2,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignFortyOne',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 40',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignFortyOne',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 40',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignFortyTwo',
		metric: 'volume',
		metrics: ['volume', 'pnl'],
		subname: 'Day 41',
		reward: 25000 * 0.5,
	},
	{
		name: 'Beta Rush',
		range: 'publicBetaTestCampaignFortyTwo',
		metric: 'pnl',
		metrics: ['volume', 'pnl'],
		subname: 'Day 41',
		reward: 25000 * 0.5,
	},
];
